### ISSUE TITLE
Four and a half Feature Requests 

### ISSUE THREAD

**Issue by Yourname942** [MelanX/curse-of-curses#2]
- [x] Please allow us to blacklist certain curses (I'd like to blacklist certain curses that are added from other mods)
- [x] Please allow us to configure how many curses we can get at a time (ie 0 curses, 1 curse, X curses) 
- [x] Please allow us to configure the start and end times (if we want them to last longer and/or happen during the day)
- [x] Please allow us to enable if curses should occur when we sleep to skip nights (if players want to be babies -> curses) 
   - Optionally you can allow curses to happen only if the players skip a configurable amount of days in a row

Thank you!

**Comment by Yourname942** [comment]
Thank you for adding these features! I have to ask, do you plan on doing this? If so, then your mod is perfect. 
 
> Optionally you can allow curses to happen only if the players skip a configurable amount of days in a row

**Comment by MelanX** [comment]
I think about it. It's a bit more effort than the other stuff. Because of this, I will not say yes. I opened another issue for that #3 to close this one
