### ISSUE TITLE
Crash on start up 1.19 forge 41.1.0

### ISSUE THREAD

**Issue by Thisguyneedshelp** [MelanX/curse-of-curses#6]
It just wont start in my modpack, heres the logs but it always says couldnt load some random fish, https://mclo.gs/CrpDyQn

**Comment by MelanX** [comment]
Maybe it’s not caused by this mod but by fish_of_thieves?

**Comment by Thisguyneedshelp** [comment]
well my modpack runs with everything else installed, there are way too many mods to see what exactly its incompatible with but at the moment it just wont run, and i really wanted it for my server too

**Comment by Thisguyneedshelp** [comment]
btw fish of thieves was a problem but curses still wont run on my modpack, heres the logs https://mclo.gs/jKHVXfn

**Comment by MelanX** [comment]
I just saw that you’re using 4.0.0 of the mod, 4.1.0 fixes crashes. Try this one out.

**Comment by Thisguyneedshelp** [comment]
im testing rn but i think thats for 1.19.1+ not 1.19

**Comment by Thisguyneedshelp** [comment]
yep, javafml needs to be 41? https://mclo.gs/9s0FxFi

**Comment by MelanX** [comment]
Yes, the latest version is for 1.19.1+ because it was at the time when 1.19.1 was already out, so nobody needs previous versions.
I think that issue is resolved now. Because I’m not "backporting" it. You could try to edit the mods.toml file in the jar, maybe it works.
